# -*- coding: utf-8 -*-
"""Lista canônica de referências do estudo, usada pelas rotinas de DOI e PubMed."""

REFS=[
 'BEEDIE, C. J.; TERRY, P. C.; LANE, A. M. The profile of mood states and athletic performance: two meta-analyses. Journal of Applied Sport Psychology, v. 12, n. 1, p. 49-68, 2000.',
 'BELGACEM, A.; SALEM, A.; YILDIZ, M. et al. Impact of competitive anxiety on mood, sleep, and physical activity levels in young karate athletes. Medicine, v. 105, 2026. DOI: 10.1097/MD.0000000000048435.',
 "BIRD, S. P.; PARSONS-SMITH, R. L.; KING, R. et al. Wellness, mood, sleep, and performance in a women's national basketball team during international competition. Journal of Human Kinetics, 2025. DOI: 10.5114/jhk/200117.",
 'BJØRNDAL, C. T.; BACHE-MATHIESEN, L. K.; GJESDAL, S. et al. An examination of training load, match activities, and health problems in Norwegian youth elite handball players over one competitive season. Frontiers in Sports and Active Living, v. 3, 635103, 2021.',
 'BÜCHEL, D.; DÖRING, M.; BAUMEISTER, J. Inter-individual differences in weekly training load in international-level handball players. Frontiers in Sports and Active Living, v. 7, 1605750, 2026.',
 'COCHRAN, W. G. The comparison of percentages in matched samples. Biometrika, v. 37, n. 3-4, p. 256-266, 1950. DOI: 10.1093/biomet/37.3-4.256.',
 'COSTA, J. A.; FIGUEIREDO, P.; NAKAMURA, F. Y. The importance of sleep in athletes. In: SLEEP MEDICINE AND THE EVOLUTION OF CONTEMPORARY SLEEP SCIENCE. London: IntechOpen, 2022. DOI: 10.5772/intechopen.102535.',
 'FERREIRA, A. B. M.; RIBEIRO, B. L. L.; MELO, A. L. L. S. et al. Effects of different training load magnitudes on sleep pattern and mood state in young soccer players. Sleep Science, v. 16, 2023. DOI: 10.1055/s-0043-1770247.',
 'FRIEDMAN, M. The use of ranks to avoid the assumption of normality implicit in the analysis of variance. Journal of the American Statistical Association, v. 32, n. 200, p. 675-701, 1937. DOI: 10.1080/01621459.1937.10503522.',
 'GARCÍA-SÁNCHEZ, C. et al. Physical demands during official competitions in elite handball: a systematic review. International Journal of Environmental Research and Public Health, v. 20, n. 4, 3353, 2023.',
 "GENTILE, A.; TRIVIĆ, T.; BIANCO, A. et al. Living in the “bubble”: athletes' psychological profile during the Sambo World Championship. Frontiers in Psychology, v. 12, 657652, 2021.",
 'HAN, C. S. Y.; PARSONS-SMITH, R. L.; TERRY, P. C. Mood profiling in Singapore: cross-cultural validation and potential applications of mood profile clusters. Frontiers in Psychology, v. 11, 665, 2020.',
 'HARRIS, C. R. et al. Array programming with NumPy. Nature, v. 585, n. 7825, p. 357-362, 2020.',
 "HENZE, A. S. et al. Athlete monitoring in handball (ATHMON HB): a survey of current practice in professional women's and men's handball. BMC Sports Science, Medicine and Rehabilitation, v. 17, n. 1, 126, 2025.",
 'HOLM, S. A simple sequentially rejective multiple test procedure. Scandinavian Journal of Statistics, v. 6, n. 2, p. 65-70, 1979.',
 'HUNTER, J. D. Matplotlib: a 2D graphics environment. Computing in Science and Engineering, v. 9, n. 3, p. 90-95, 2007.',
 'KARCHER, C.; BUCHHEIT, M. On-court demands of elite handball, with special reference to playing positions. Sports Medicine, v. 44, n. 6, p. 797-814, 2014.',
 'KELLMANN, M. et al. Recovery and performance in sport: consensus statement. International Journal of Sports Physiology and Performance, v. 13, n. 2, p. 240-245, 2018.',
 'KENDALL, M. G.; SMITH, B. B. The problem of m rankings. The Annals of Mathematical Statistics, v. 10, n. 3, p. 275-287, 1939. DOI: 10.1214/aoms/1177732186.',
 'LEW, P. C. F.; PARSONS-SMITH, R. L.; LAMONT-MILLS, A. et al. Cross-cultural validation of the Malaysian Mood Scale and tests of between-group mood differences. International Journal of Environmental Research and Public Health, v. 20, n. 4, 3348, 2023.',
 'LOCHBAUM, M. et al. The Profile of Mood States and athletic performance: a meta-analysis of published studies. European Journal of Investigation in Health, Psychology and Education, v. 11, n. 1, p. 50-70, 2021.',
 'LUOJUMÄKI, R.; RUIZ, M. C.; ADIE, J. et al. Exploring mood profile clusters across physical activity level, gender and age. European Journal of Sport Science, 2026. DOI: 10.1002/ejsc.70131.',
 "McFADDEN, B. A.; WALKER, A. J.; BOZZINI, B. N. et al. Psychological and physiological changes in response to the cumulative demands of a women's division I collegiate soccer season. Journal of Strength and Conditioning Research, v. 35, n. 12, p. 3405-3414, 2021.",
 'McNEMAR, Q. Note on the sampling error of the difference between correlated proportions or percentages. Psychometrika, v. 12, n. 2, p. 153-157, 1947. DOI: 10.1007/BF02295996.',
 'MEEUSEN, R. et al. Prevention, diagnosis, and treatment of the overtraining syndrome: joint consensus statement of the European College of Sport Science and the American College of Sports Medicine. Medicine and Science in Sports and Exercise, v. 45, n. 1, p. 186-205, 2013.',
 'MORGAN, W. P. Selected psychological factors limiting performance: a mental health model. In: CLARKE, D. H.; ECKERT, H. M. (org.). Limits of human performance. Champaign: Human Kinetics, 1985. p. 70-80.',
 'MORGAN, W. P. Test of champions: the iceberg profile. Psychology Today, v. 14, p. 92-108, 1980.',
 'PAGE, E. B. Ordered hypotheses for multiple treatments: a significance test for linear ranks. Journal of the American Statistical Association, v. 58, n. 301, p. 216-230, 1963.',
 'PARSONS-SMITH, R. L.; TERRY, P. C.; MACHIN, M. A. Identification and description of novel mood profile clusters. Frontiers in Psychology, v. 8, 1958, 2017.',
 'PEREZ ARMENDARIZ, M. L.; SPYROU, K.; ALCARÁZ, P. E. Match demands of female team sports: a scoping review. Biology of Sport, v. 41, n. 3, p. 175-199, 2024.',
 'RAFNSSON, E. T.; MYKLEBUST, G.; VALDIMARSSON, Ö. et al. Association between training load, intensity, and overuse problems during pre-season in elite handball. Translational Sports Medicine, v. 4, n. 6, p. 858-865, 2021.',
 'REYNOSO-SÁNCHEZ, L. F.; PÉREZ-VERDUZCO, G.; CELESTINO SÁNCHEZ, M. A. et al. Competitive recovery-stress and mood states in Mexican youth athletes. Frontiers in Psychology, v. 11, 627828, 2021.',
 'ROHLFS, I. C. P. M. et al. Psychometric characteristics of the Brazil Mood Scale among youth and elite athletes using two response time frames. Sports, v. 11, n. 12, 244, 2023.',
 'ROHLFS, I. C. P. M.; NOCE, F.; WILKE, C. F. et al. Mood states, injury status, and countermovement jump performance in Brazilian high-performance athletes. Sports, v. 13, n. 9, 303, 2025.',
 'ROHLFS, I. C. P. M.; NOCE, F.; WILKE, C. F. Prevalence of specific mood profile clusters among elite and youth athletes at a Brazilian sports club. Sports, v. 12, n. 7, 195, 2024.',
 'ROHLFS, I. C. P. M.; ROTTA, T. M.; LUFT, C. D. B. et al. A Escala de Humor de Brunel (BRUMS): instrumento para detecção precoce da síndrome do excesso de treinamento. Revista Brasileira de Medicina do Esporte, v. 14, n. 3, p. 176-181, 2008.',
 'SAAL, C.; RHEINSBERG, P.; BAUMGART, C. How different defensive formations affect physical match demands in the German Handball Bundesliga. Frontiers in Sports and Active Living, v. 8, 1811523, 2026.',
 'SAHLI, H.; SAHLI, F.; SAIDANE, M. et al. Testing the psychometric properties of an Arabic version of the Brunel Mood Scale among physical education students. European Journal of Investigation in Health, Psychology and Education, v. 13, n. 8, p. 1539-1552, 2023.',
 'SAW, A. E.; MAIN, L. C.; GASTIN, P. B. Monitoring the athlete training response: subjective self-reported measures trump commonly used objective measures: a systematic review. British Journal of Sports Medicine, v. 50, n. 5, p. 281-291, 2016.',
 'SAWCZUK, T.; JONES, B.; SCANTLEBURY, S. et al. Influence of perceptions of sleep on well-being in youth athletes. Journal of Strength and Conditioning Research, v. 35, n. 4, p. 1066-1073, 2021.',
 'SHROUT, P. E.; FLEISS, J. L. Intraclass correlations: uses in assessing rater reliability. Psychological Bulletin, v. 86, n. 2, p. 420-428, 1979. DOI: 10.1037/0033-2909.86.2.420.',
 'TERRY, P. C.; LANE, A. M. Normative values for the profile of mood states for use with athletic samples. Journal of Applied Sport Psychology, v. 12, n. 1, p. 93-109, 2000.',
 'TERRY, P. C.; LANE, A. M.; LANE, H. J.; KEOHANE, L. Development and validation of a mood measure for adolescents. Journal of Sports Sciences, v. 17, n. 11, p. 861-872, 1999.',
 'TERRY, P. C.; PARSONS-SMITH, R. L. Mood profiling for sustainable mental health among athletes. Sustainability, v. 13, n. 11, 6116, 2021.',
 'TERRY, P. C.; PARSONS-SMITH, R. L.; SKURVYDAS, A. et al. Physical activity and healthy habits influence mood profile clusters in a Lithuanian population. Sustainability, v. 14, n. 16, 10006, 2022.',
 'TERRY, P. C.; PARSONS-SMITH, R. L.; VLACHOPOULOS, S. P. Mood profile clusters among Greek exercise participants and inactive adults. Sci, v. 6, n. 2, 18, 2024.',
 'TERRY, P. C.; SKURVYDAS, A.; LISINSKIENĖ, A. et al. Validation of a Lithuanian-language version of the Brunel Mood Scale: the BRUMS-LTU. International Journal of Environmental Research and Public Health, v. 19, n. 8, 4867, 2022.',
 'TERWEE, C. B. et al. Quality criteria were proposed for measurement properties of health status questionnaires. Journal of Clinical Epidemiology, v. 60, n. 1, p. 34-42, 2007.',
 'VIRTANEN, P. et al. SciPy 1.0: fundamental algorithms for scientific computing in Python. Nature Methods, v. 17, n. 3, p. 261-272, 2020.',
 'VLACHOPOULOS, S. P.; LANE, A. M.; TERRY, P. C. A Greek translation of the Brunel Mood Scale: initial validation among exercise participants and inactive adults. Sports, v. 11, n. 12, 234, 2023.',
 'WILCOXON, F. Individual comparisons by ranking methods. Biometrics Bulletin, v. 1, n. 6, p. 80-83, 1945. DOI: 10.2307/3001968.',
 'WILKE, C. F.; WANNER, S. P.; SANTOS, W. H. M. et al. Influence of faster and slower recovery-profile classifications, self-reported sleep, acute training load, and phase of the microcycle on perceived recovery in football players. International Journal of Sports Physiology and Performance, v. 15, n. 8, p. 1148-1156, 2020.',
]
